[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "groq>=0.34.0",
    "python-telegram-bot>=22.5",
]
